version: '2'
services:
  wasp:
    image: agilelab/wasp
    container_name: wasp
    ports:
      - "4040:4040"
      - "9000:9000"
      - "9999:9999"
    volumes:
      - "./wasp/wasp-container-all-services.conf:/opt/wasp/wasp-container.conf"
networks:
  default:
    external:
      name: wasp-docker